version: "3"

services:
  app:
    container_name: express-docker
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/src/app/
    command: yarn start
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "3001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "3002:8080"
    volumes:
      - ../docs/api/:/docs/api
    environment:
      - SWAGGER_JSON=/docs/api/v1/swagger.yaml
  # redis:
  # postgres:
  # etc...